import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "@/app/globals.css";
import AuthProvider from "@/Components/AuthProvider";

const jost = Jost({
  subsets: ["latin"],
  variable: "--font-jost",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.boxicons.com/3.0.7/fonts/basic/boxicons.min.css"
          rel="stylesheet"
        />
      </head>
      <body className={jost.variable}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
