import type { Metadata } from "next";
import { Geist, Geist_Mono, Jost } from "next/font/google";
import "@/app/globals.css";
import Header from "@/Components/Header";
import Footer from "@/Components/Footer";

const jost = Jost({
  subsets: ["latin"],
  variable: "--font-jost",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      {children}
      <Footer />
    </>
  );
}
