import type { Metadata } from "next";
import { Geist, Geist_Mono, Jost } from "next/font/google";
import "@/app/globals.css";

const jost = Jost({
  subsets: ["latin"],
  variable: "--font-jost",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="min-h-screen bg-gray-100">
      {children}
    </main>
  );
}
